services:
    sonata.admin.category:
        class: Stas\ProductBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Category" }
        arguments:
            - ~
            - Stas\ProductBundle\Entity\Category
            - ~
            
    sonata.admin.product:
        class: Stas\ProductBundle\Admin\ProductAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Product" }
        arguments:
            - ~
            - Stas\ProductBundle\Entity\Product
            - ~