parameters:
#    stas_product.example.class: Stas\ProductBundle\Example

services:
#    stas_product.example:
#        class: %stas_product.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
